[package]
name = "atoman"
description = "A library for managing shared asynchronous data across threads. Provides safe concurrent access to application state with automatic synchronization and minimizes the need for manual lock management."
keywords = ["atomic", "static", "flag", "state", "config"]
categories = ["development-tools", "rust-patterns"]
version = "0.4.1"
license = "MIT"
authors = ["Bulat Sh. <synapdrake@ya.ru>"]
repository = "https://github.com/fuderis/atoman-rs"
readme = "README.md"
edition = "2024"

[dependencies]
arc-swap = "1.8.0"
once_cell = "1.21.3"
macron = { version = "0.1.18", features = ["derive", "string"] }
tokio = { version = "1.49.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"], optional = true }
serde_json = { version = "1.0.148", optional = true }
toml = { version = "1.0.0", optional = true }
log = { version = "0.4.29", optional = true }
chrono = { version = "0.4.42", features = ["serde"], optional = true }
bytes = { version = "1.11.1", optional = true }
regex = { version = "1.12.3", optional = true }
fuzzy-cmp = { version = "0.1.3", optional = true }
tracing = { version = "0.1.44", optional = true }
tracing-subscriber = { version = "0.3.23", optional = true }

[features]
full = ["channel", "file", "config", "logger", "trace", "search"]
config = ["json-config", "toml-config", "dep:chrono"]
json-config = ["dep:serde", "dep:serde_json"]
toml-config = ["dep:serde", "dep:toml"]
logger = ["dep:tracing", "dep:tracing-subscriber",  "dep:chrono", "dep:bytes"]
trace = []
channel = ["dep:serde", "dep:serde_json"]
file = ["dep:bytes", "dep:chrono", "dep:serde"]
search = ["dep:regex", "dep:fuzzy-cmp"]
tracing = ["dep:tracing"]
tracing-subscriber = ["dep:tracing-subscriber"]
trace-lock = ["logger"]
