[package]
name = "atoman-log"
description = "The log implementation macros for atoman crate"
version = "0.1.2"
license = "MIT"
authors = ["Bulat Sh. <synapdrake@ya.ru>"]
repository = "https://github.com/fuderis/atoman-rs/blob/main/crates/log"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
